lsi: false
safe: true
source: https://github.com/KevinGriffin-new/kevingriffin-new.github.io/
theme: architect
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
