lsi: false
safe: true
source: https://github.com/KevinGriffin-new/kevingriffin-new.github.io/
theme:  jekyll-theme-minimal
title:  Testing Jekyll themes and github pages
description: test page
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
